services:

        mqtt_broker:
            extends:
                file: mqtt_broker/app.yml
                service: app
            networks:
                internal:
                    aliases:
                        - mqtt.docker.local
            logging:
                    driver: syslog
                    options:
                            tag: docker-mqtt-broker
            restart: unless-stopped
